name: novasocial_admin
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.2.0
  copy_with_extension: ^5.0.0
  cupertino_icons: ^1.0.2
  cupertino_back_gesture: ^0.1.0
  firebase_core: ^2.4.0
  flutter_native_splash: 
  flutter_screen_lock: ^9.0.0+1
  font_awesome_flutter: ^10.3.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  json_serializable: ^6.5.4
  provider: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  freezed: ^2.3.2
  package_rename: ^1.0.0+1


flutter:

  uses-material-design: true

  assets:
    - assets/images/

package_rename_config:
  android:
    app_name: Nova Social Admin
    package_name: club.novasocial.admin

  ios:
    app_name: Nova Social Admin
    bundle_name: nova-social
    package_name: club.novasocial.admin

  web:
    app_name: Nova Social
    description: 

flutter_native_splash:
  color: "#1E1E1E"
  image: assets/images/nova_logo.png
  color_dark: "#1E1E1E"
  image_dark: assets/images/nova_logo.png

  android_12:
    image: assets/images/nova_logo.png
    icon_background_color: "#1E1E1E"
    image_dark: assets/images/nova_logo.png
    icon_background_color_dark: "#1E1E1E"
  
  web: false

  # assets:
  #   - assets/icons/


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
